export const supabaseUrl = 'https://rrschuyagooukketxorg.supabase.co';
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyc2NodXlhZ29vdWtrZXR4b3JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjQ3MjAsImV4cCI6MjA2NzIwMDcyMH0.4u-rLVImKHptlQ76u1pEjIbcG63Idbxg_ELQ7OA1K5M';
